require 'rspec/core/rake_task'

require 'simplecov'
SimpleCov.start do
  add_filter '/spec/'
  add_group 'Models', 'lib/web/models'
end if ENV["COVERAGE"]

task :default => :test

# And add rake task spec:coverage to lib/tasks/coverage.rake:
desc "Create rspec coverage"
task :coverage do
    ENV['COVERAGE'] = 'true'
    `rspec spec`
    `open coverage/index.html`
end

desc "Running the tests for production"
task :test => :spec do
  ENV["TEST_ORCHESTRATION_PROVIDER"] ||= "production"
  `rspec spec`
end
