require 'rspec/core/rake_task'

require 'simplecov'
require 'simplecov-rcov'

SimpleCov.formatter = SimpleCov::Formatter::RcovFormatter
SimpleCov.start do
    add_filter "/spec/"
end

task :default => :test

desc "Running the tests for production"

task :test => :spec do
  ENV["TEST_ORCHESTRATION_PROVIDER"] ||= "production"
  sh %{rspec spec}
end
