require 'rspec/core/rake_task'

task :default => :test

desc "Create rspec coverage"
task :coverage do
    ENV['COVERAGE'] = 'true'
    `rspec spec`
    `open coverage/index.html`
end

desc "Running the tests for production"
task :test do
  ENV["TEST_ORCHESTRATION_PROVIDER"] ||= "production"
  sh %Q{ rspec spec }
end
